[tool.isort]
profile = "black"
src_paths = "bds_sampler"
multi_line_output = 3

[tool.pydocstyle]
match_dir = "bds_sampler"
convention = "numpy"
add_select = ["D402","D415","D417"]

[tool.pytest.ini_options]
addopts = "-W error"

[tool.mypy]
files = "bds_sampler"
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
implicit_reexport = false
# this is strict!
# disallow_untyped_defs = true
show_column_numbers = true
show_error_codes = true
ignore_missing_imports = true
